### ISSUE TITLE
CT Converting circular structure to JSON

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/projectile-data-lab#105]
```
projectile-data-lab : fuzz : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1706221107153/projectile-data-lab/projectile-data-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1706221107153%22%2C%22timestamp%22%3A1706222237193%7D&brand=phet&ea&fuzz
Query: brand=phet&ea&fuzz
Uncaught TypeError: Converting circular structure to JSON
--> starting at object with constructor 'Tandem'
| property 'children' -> object with constructor 'Object'
| property 'launcherMechanismProperty' -> object with constructor 'Tandem'
--- property 'parentTandem' closes the circle
TypeError: Converting circular structure to JSON
at JSON.stringify
at stringify (validate.ts:31:35)
at validate (ReadOnlyProperty.ts:315:14)
at _notifyListeners (ReadOnlyProperty.ts:281:13)
at unguardedSet (ReadOnlyProperty.ts:265:11)
at set (DynamicProperty.ts:234:10)
at listener (ReadOnlyProperty.ts:430:4)
at link (DynamicProperty.ts:250:38)
at listener (TinyEmitter.ts:123:8)
at emit (ReadOnlyProperty.ts:334:22)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1706221107153%2Fprojectile-data-lab%2Fprojectile-data-lab_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz&duration=90000&testInfo=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1706221107153%22%2C%22timestamp%22%3A1706222237193%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1706221107153%2Fprojectile-data-lab%2Fprojectile-data-lab_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz&duration=90000&testInfo=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1706221107153%22%2C%22timestamp%22%3A1706222237193%7D
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1706221107153/projectile-data-lab/projectile-data-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1706221107153%22%2C%22timestamp%22%3A1706222237193%7D&brand=phet&ea&fuzz
[CONSOLE] enabling assert
[CONSOLE] continuous-test-load
[PAGE ERROR] Error: TypeError: Converting circular structure to JSON
--> starting at object with constructor 'Tandem'
| property 'children' -> object with constructor 'Object'
| property 'launcherMechanismProperty' -> object with constructor 'Tandem'
--- property 'parentTandem' closes the circle
at JSON.stringify (<anonymous>)
at validate (http://128.138.93.172/continuous-testing/ct-snapshots/1706221107153/chipper/dist/js/axon/js/validate.js:27:36)
at DynamicProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1706221107153/chipper/dist/js/axon/js/ReadOnlyProperty.js:239:15)
at DynamicProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1706221107153/chipper/dist/js/axon/js/ReadOnlyProperty.js:205:14)
at DynamicProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1706221107153/chipper/dist/js/axon/js/ReadOnlyProperty.js:190:12)
at DynamicProperty.onPropertyPropertyChange (http://128.138.93.172/continuous-testing/ct-snapshots/1706221107153/chipper/dist/js/axon/js/DynamicProperty.js:182:11)
at Property.link (http://128.138.93.172/continuous-testing/ct-snapshots/1706221107153/chipper/dist/js/axon/js/ReadOnlyProperty.js:345:5)
at DynamicProperty.onPropertyChange (http://128.138.93.172/continuous-testing/ct-snapshots/1706221107153/chipper/dist/js/axon/js/DynamicProperty.js:198:37)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1706221107153/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1706221107153/chipper/dist/js/axon/js/ReadOnlyProperty.js:256:23)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 1/25/2024, 3:18:27 PM

----------------------------------

projectile-data-lab : fuzz : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1706221107153/projectile-data-lab/projectile-data-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1706221107153%22%2C%22timestamp%22%3A1706223603938%7D&brand=phet&ea&fuzz
Query: brand=phet&ea&fuzz
TypeError: cyclic object value
validate@http://127.0.0.1/continuous-testing/ct-snapshots/1706221107153/chipper/dist/js/axon/js/validate.js:27:36
at stringify (validate.ts:31:35)
at validate (ReadOnlyProperty.ts:315:14)
at _notifyListeners (ReadOnlyProperty.ts:281:13)
at unguardedSet (ReadOnlyProperty.ts:265:11)
at set (DynamicProperty.ts:234:10)
at (ReadOnlyProperty.ts:430:14)
at link (DynamicProperty.ts:250:38)
at (TinyEmitter.ts:123:18)
at emit (ReadOnlyProperty.ts:334:22)
at _notifyListeners (ReadOnlyProperty.ts:281:13)
at unguardedSet (ReadOnlyProperty.ts:265:11)
at set (Property.ts:65:10)
at set (RectangularRadioButton.ts:148:50)
at (TinyEmitter.ts:123:18)
at emit (Emitter.ts:62:21)
at emit (RectangularRadioButton.ts:184:24)
at fire (RectangularRadioButton.ts:153:13)
at (TinyEmitter.ts:123:18)
at emit (ReadOnlyProperty.ts:334:22)
at _notifyListeners (ReadOnlyProperty.ts:281:13)
at unguardedSet (ReadOnlyProperty.ts:265:11)
at set (Property.ts:65:10)
at set (ButtonModel.ts:191:24)
at (TinyEmitter.ts:123:18)
at emit (ReadOnlyProperty.ts:334:22)
at _notifyListeners (ReadOnlyProperty.ts:281:13)
at unguardedSet (ReadOnlyProperty.ts:265:11)
at set (Property.ts:54:10)
at (PressListener.ts:747:4)
at apply (PhetioAction.ts:162:16)
at execute (PressListener.ts:508:24)
at release (PressListener.ts:851:11)
at inputEvent (Input.ts:1907:69)
at dispatchToListeners (Input.ts:1853:9)
at dispatchEvent (Input.ts:1657:9)
at upEvent (Input.ts:401:11)
at apply (PhetioAction.ts:162:16)
at execute (Input.ts:1223:23)
at mouseUp (InputFuzzer.js:275:26)
at mouseToggle (InputFuzzer.js:40:11)
at action (InputFuzzer.js:107:6)
at fuzzEvents (SimDisplay.ts:210:23)
at fuzzInputEvents (Sim.ts:986:44)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
at requestAnimationFrame (Sim.ts:978:11)
[URL] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1706221107153%2Fprojectile-data-lab%2Fprojectile-data-lab_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz&duration=90000&testInfo=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1706221107153%22%2C%22timestamp%22%3A1706223603938%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1706221107153%2Fprojectile-data-lab%2Fprojectile-data-lab_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz&duration=90000&testInfo=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1706221107153%22%2C%22timestamp%22%3A1706223603938%7D
[ATTACHED]
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1706221107153/projectile-data-lab/projectile-data-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1706221107153%22%2C%22timestamp%22%3A1706223603938%7D&brand=phet&ea&fuzz
[CONSOLE] enabling assert
[CONSOLE] [JavaScript Warning: "An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1706221107153/chipper/dist/js/tambo/js/phetAudioContext.js" line: 15}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1706221107153/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1706221107153/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1706221107153/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed:
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1706221107153/chipper/dist/js/scenery/js/util/Utils.js" line: 446}]
[CONSOLE] continuous-test-load
[CONSOLE] continuous-test-error
[PAGE ERROR] TypeError: cyclic object value
[CONSOLE] Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
[CONSOLE] Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
[CONSOLE] Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
[CONSOLE] Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: reentry detected, value=[object Object], oldValue=[object Object]

id: "Sparky Node Firefox"
Snapshot from 1/25/2024, 3:18:27 PM
```

**Comment by samreid** [comment]
Thanks @KatieWoe, @matthew-blackman and I fixed it. Closing.
