### ISSUE TITLE
CT Build failed with status code 1:

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/projectile-data-lab#14]
```
projectile-data-lab : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (projectile-data-lab, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 6258ms
>> Unused string: key=meters, value=m
>> Unused string: key=meanMPattern, value={{mean}} m
>> Unused string: key=standardDeviationMPattern, value={{standardDeviation}} m
>> Unused string: key=nEqualsSampleSizePattern, value=n = {{sampleSize}}
>> Production minification complete: 31167ms (2628716 bytes)
>> Debug minification complete: 0ms (24077159 bytes)
Building brand: phet-io
>> Webpack build complete: 4778ms
>> Unused string: key=meters, value=m
>> Unused string: key=meanMPattern, value={{mean}} m
>> Unused string: key=standardDeviationMPattern, value={{standardDeviation}} m
>> Unused string: key=nEqualsSampleSizePattern, value=n = {{sampleSize}}
>> Production minification complete: 27664ms (2646194 bytes)
>> Debug minification complete: 28790ms (2945027 bytes)
>> tsc complete: 24026ms
>> tsc complete: 4747ms
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION]: use let instead of const when awaiting values in PhET-iO "examples" files
at generateAndWriteClientGuide (/data/share/phet/continuous-testing/ct-main/ct-snapshots/1702379162015/chipper/js/grunt/copySupplementalPhetioFiles.js:655:25)
at handleClientGuides (/data/share/phet/continuous-testing/ct-main/ct-snapshots/1702379162015/chipper/js/grunt/copySupplementalPhetioFiles.js:595:3)
at module.exports (/data/share/phet/continuous-testing/ct-main/ct-snapshots/1702379162015/chipper/js/grunt/copySupplementalPhetioFiles.js:384:3)
at async module.exports (/data/share/phet/continuous-testing/ct-main/ct-snapshots/1702379162015/chipper/js/grunt/buildRunnable.js:388:5)
at async /data/share/phet/continuous-testing/ct-main/ct-snapshots/1702379162015/chipper/js/grunt/Gruntfile.js:304:15
at async Object.startAsync (/data/share/phet/continuous-testing/ct-main/ct-snapshots/1702379162015/perennial-alias/js/common/phetTimingLog.js:133:20)
at async /data/share/phet/continuous-testing/ct-main/ct-snapshots/1702379162015/chipper/js/grunt/Gruntfile.js:303:13
at async Object.startAsync (/data/share/phet/continuous-testing/ct-main/ct-snapshots/1702379162015/perennial-alias/js/common/phetTimingLog.js:133:20)
at async /data/share/phet/continuous-testing/ct-main/ct-snapshots/1702379162015/chipper/js/grunt/Gruntfile.js:230:7
at async wrap (/data/share/phet/continuous-testing/ct-main/ct-snapshots/1702379162015/chipper/js/grunt/Gruntfile.js:69:7)
Full Error details:
AssertionError [ERR_ASSERTION]: use let instead of const when awaiting values in PhET-iO "examples" files
Snapshot from 12/12/2023, 4:06:02 AM

----------------------------------

projectile-data-lab : phet-io-state-fuzz : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/phet-io-wrappers/state/?sim=projectile-data-lab&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1702379162015%22%2C%22timestamp%22%3A1702379867321%7D
Uncaught Error: Assertion failed: members should have the correct length. sampleNumber = 1, members.length = 0, this.sampleSize = 2
Error: Assertion failed: members should have the correct length. sampleNumber = 1, members.length = 0, this.sampleSize = 2
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/assert/js/assert.js:28:13)
at assert (SamplingField.ts:95:16)
at getSamples (HistogramNode.ts:200:30)
at updateHistogram (HistogramNode.ts:222:49)
at listener (TinyEmitter.ts:123:8)
at emit (ReadOnlyProperty.ts:329:22)
at _notifyListeners (ReadOnlyProperty.ts:377:46)
at listener (PropertyStateHandler.ts:273:40)
at attemptToApplyPhases (PropertyStateHandler.ts:193:11)
at undeferAndNotifyProperties (PropertyStateHandler.ts:88:11)
[URL] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1702379162015%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dprojectile-data-lab%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz&testInfo=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1702379162015%22%2C%22timestamp%22%3A1702379867321%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1702379162015%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dprojectile-data-lab%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz&testInfo=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1702379162015%22%2C%22timestamp%22%3A1702379867321%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/phet-io-wrappers/state/?sim=projectile-data-lab&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1702379162015%22%2C%22timestamp%22%3A1702379867321%7D
[NAVIGATED] about:blank
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/projectile-data-lab/projectile-data-lab_en.html?brand=phet-io&ea&debugger&postMessageOnError&sim=projectile-data-lab&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1702379162015%22%2C%22timestamp%22%3A1702379867321%7D&frameTitle=source
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/projectile-data-lab/projectile-data-lab_en.html?brand=phet-io&ea&debugger&postMessageOnError&sim=projectile-data-lab&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1702379162015%22%2C%22timestamp%22%3A1702379867321%7D&frameTitle=destination
[CONSOLE] enabling assert
[CONSOLE] enabling assert
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] Assertion failed: members should have the correct length. sampleNumber = 1, members.length = 0, this.sampleSize = 2
[PAGE ERROR] Error: Error: Assertion failed: members should have the correct length. sampleNumber = 1, members.length = 0, this.sampleSize = 2
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/assert/js/assert.js:28:13)
at SamplingField.getSamples (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/projectile-data-lab/js/sampling/model/SamplingField.js:68:17)
at updateHistogram (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/projectile-data-lab/js/common/view/HistogramNode.js:162:31)
at http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/projectile-data-lab/js/common/view/HistogramNode.js:181:49
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at NumberProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/ReadOnlyProperty.js:250:23)
at PhaseCallback.listener (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/ReadOnlyProperty.js:295:47)
at PropertyStateHandler.attemptToApplyPhases (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/PropertyStateHandler.js:220:41)
at PropertyStateHandler.undeferAndNotifyProperties (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/PropertyStateHandler.js:149:12)
at http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/PropertyStateHandler.js:54:12
[PAGE ERROR] Error: Error: Assertion failed: members should have the correct length. sampleNumber = 1, members.length = 0, this.sampleSize = 2
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/assert/js/assert.js:28:13)
at SamplingField.getSamples (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/projectile-data-lab/js/sampling/model/SamplingField.js:68:17)
at updateHistogram (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/projectile-data-lab/js/common/view/HistogramNode.js:162:31)
at http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/projectile-data-lab/js/common/view/HistogramNode.js:181:49
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at NumberProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/ReadOnlyProperty.js:250:23)
at PhaseCallback.listener (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/ReadOnlyProperty.js:295:47)
at PropertyStateHandler.attemptToApplyPhases (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/PropertyStateHandler.js:220:41)
at PropertyStateHandler.undeferAndNotifyProperties (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/PropertyStateHandler.js:149:12)
at http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/PropertyStateHandler.js:54:12
[CONSOLE] continuous-test-wrapper-error
[CONSOLE] continuous-test-wrapper-error

id: "Sparky Node Puppeteer"
Snapshot from 12/12/2023, 4:06:02 AM

----------------------------------

projectile-data-lab : phet-io-state-fuzz : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/phet-io-wrappers/state/?sim=projectile-data-lab&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1702379162015%22%2C%22timestamp%22%3A1702385395747%7D
Uncaught Error: Assertion failed: members should have the correct length. sampleNumber = 1, members.length = 0, this.sampleSize = 40
Error: Assertion failed: members should have the correct length. sampleNumber = 1, members.length = 0, this.sampleSize = 40
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/assert/js/assert.js:28:13)
at assert (SamplingField.ts:95:16)
at getSamples (HistogramNode.ts:200:30)
at updateHistogram (HistogramNode.ts:222:49)
at listener (TinyEmitter.ts:123:8)
at emit (ReadOnlyProperty.ts:329:22)
at _notifyListeners (ReadOnlyProperty.ts:377:46)
at listener (PropertyStateHandler.ts:273:40)
at attemptToApplyPhases (PropertyStateHandler.ts:193:11)
at undeferAndNotifyProperties (PropertyStateHandler.ts:88:11)
[URL] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1702379162015%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dprojectile-data-lab%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz&testInfo=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1702379162015%22%2C%22timestamp%22%3A1702385395747%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1702379162015%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dprojectile-data-lab%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz&testInfo=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1702379162015%22%2C%22timestamp%22%3A1702385395747%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/phet-io-wrappers/state/?sim=projectile-data-lab&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1702379162015%22%2C%22timestamp%22%3A1702385395747%7D
[NAVIGATED] about:blank
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/projectile-data-lab/projectile-data-lab_en.html?brand=phet-io&ea&debugger&postMessageOnError&sim=projectile-data-lab&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1702379162015%22%2C%22timestamp%22%3A1702385395747%7D&frameTitle=source
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/projectile-data-lab/projectile-data-lab_en.html?brand=phet-io&ea&debugger&postMessageOnError&sim=projectile-data-lab&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1702379162015%22%2C%22timestamp%22%3A1702385395747%7D&frameTitle=destination
[CONSOLE] enabling assert
[CONSOLE] enabling assert
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] Assertion failed: members should have the correct length. sampleNumber = 1, members.length = 0, this.sampleSize = 40
[PAGE ERROR] Error: Error: Assertion failed: members should have the correct length. sampleNumber = 1, members.length = 0, this.sampleSize = 40
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/assert/js/assert.js:28:13)
at SamplingField.getSamples (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/projectile-data-lab/js/sampling/model/SamplingField.js:68:17)
at updateHistogram (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/projectile-data-lab/js/common/view/HistogramNode.js:162:31)
at http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/projectile-data-lab/js/common/view/HistogramNode.js:181:49
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at NumberProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/ReadOnlyProperty.js:250:23)
at PhaseCallback.listener (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/ReadOnlyProperty.js:295:47)
at PropertyStateHandler.attemptToApplyPhases (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/PropertyStateHandler.js:220:41)
at PropertyStateHandler.undeferAndNotifyProperties (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/PropertyStateHandler.js:149:12)
at http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/PropertyStateHandler.js:54:12
[PAGE ERROR] Error: Error: Assertion failed: members should have the correct length. sampleNumber = 1, members.length = 0, this.sampleSize = 40
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/assert/js/assert.js:28:13)
at SamplingField.getSamples (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/projectile-data-lab/js/sampling/model/SamplingField.js:68:17)
at updateHistogram (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/projectile-data-lab/js/common/view/HistogramNode.js:162:31)
at http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/projectile-data-lab/js/common/view/HistogramNode.js:181:49
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at NumberProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/ReadOnlyProperty.js:250:23)
at PhaseCallback.listener (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/ReadOnlyProperty.js:295:47)
at PropertyStateHandler.attemptToApplyPhases (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/PropertyStateHandler.js:220:41)
at PropertyStateHandler.undeferAndNotifyProperties (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/PropertyStateHandler.js:149:12)
at http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/PropertyStateHandler.js:54:12
[CONSOLE] continuous-test-wrapper-error
[CONSOLE] continuous-test-wrapper-error

id: "Sparky Node Puppeteer"
Snapshot from 12/12/2023, 4:06:02 AM

----------------------------------

projectile-data-lab : phet-io-state-fuzz : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/phet-io-wrappers/state/?sim=projectile-data-lab&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1702379162015%22%2C%22timestamp%22%3A1702390314415%7D
Uncaught Error: Assertion failed: members should have the correct length. sampleNumber = 1, members.length = 1, this.sampleSize = 2
Error: Assertion failed: members should have the correct length. sampleNumber = 1, members.length = 1, this.sampleSize = 2
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/assert/js/assert.js:28:13)
at assert (SamplingField.ts:95:16)
at getSamples (HistogramNode.ts:200:30)
at updateHistogram (HistogramNode.ts:222:49)
at listener (TinyEmitter.ts:123:8)
at emit (ReadOnlyProperty.ts:329:22)
at _notifyListeners (ReadOnlyProperty.ts:377:46)
at listener (PropertyStateHandler.ts:273:40)
at attemptToApplyPhases (PropertyStateHandler.ts:193:11)
at undeferAndNotifyProperties (PropertyStateHandler.ts:88:11)
[URL] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1702379162015%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dprojectile-data-lab%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz&testInfo=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1702379162015%22%2C%22timestamp%22%3A1702390314415%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1702379162015%2Fphet-io-wrappers%2Fstate%2F%3Fsim%3Dprojectile-data-lab%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz&testInfo=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1702379162015%22%2C%22timestamp%22%3A1702390314415%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/phet-io-wrappers/state/?sim=projectile-data-lab&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1702379162015%22%2C%22timestamp%22%3A1702390314415%7D
[NAVIGATED] about:blank
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/projectile-data-lab/projectile-data-lab_en.html?brand=phet-io&ea&debugger&postMessageOnError&sim=projectile-data-lab&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1702379162015%22%2C%22timestamp%22%3A1702390314415%7D&frameTitle=source
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/projectile-data-lab/projectile-data-lab_en.html?brand=phet-io&ea&debugger&postMessageOnError&sim=projectile-data-lab&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1702379162015%22%2C%22timestamp%22%3A1702390314415%7D&frameTitle=destination
[CONSOLE] enabling assert
[CONSOLE] enabling assert
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] Assertion failed: members should have the correct length. sampleNumber = 1, members.length = 1, this.sampleSize = 2
[PAGE ERROR] Error: Error: Assertion failed: members should have the correct length. sampleNumber = 1, members.length = 1, this.sampleSize = 2
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/assert/js/assert.js:28:13)
at SamplingField.getSamples (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/projectile-data-lab/js/sampling/model/SamplingField.js:68:17)
at updateHistogram (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/projectile-data-lab/js/common/view/HistogramNode.js:162:31)
at http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/projectile-data-lab/js/common/view/HistogramNode.js:181:49
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at NumberProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/ReadOnlyProperty.js:250:23)
at PhaseCallback.listener (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/ReadOnlyProperty.js:295:47)
at PropertyStateHandler.attemptToApplyPhases (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/PropertyStateHandler.js:220:41)
at PropertyStateHandler.undeferAndNotifyProperties (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/PropertyStateHandler.js:149:12)
at http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/PropertyStateHandler.js:54:12
[PAGE ERROR] Error: Error: Assertion failed: members should have the correct length. sampleNumber = 1, members.length = 1, this.sampleSize = 2
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/assert/js/assert.js:28:13)
at SamplingField.getSamples (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/projectile-data-lab/js/sampling/model/SamplingField.js:68:17)
at updateHistogram (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/projectile-data-lab/js/common/view/HistogramNode.js:162:31)
at http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/projectile-data-lab/js/common/view/HistogramNode.js:181:49
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at NumberProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/ReadOnlyProperty.js:250:23)
at PhaseCallback.listener (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/ReadOnlyProperty.js:295:47)
at PropertyStateHandler.attemptToApplyPhases (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/PropertyStateHandler.js:220:41)
at PropertyStateHandler.undeferAndNotifyProperties (http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/PropertyStateHandler.js:149:12)
at http://128.138.93.172/continuous-testing/ct-snapshots/1702379162015/chipper/dist/js/axon/js/PropertyStateHandler.js:54:12
[CONSOLE] continuous-test-wrapper-error
[CONSOLE] continuous-test-wrapper-error

id: "Sparky Node Puppeteer"
Snapshot from 12/12/2023, 4:06:02 AM
```

**Comment by samreid** [comment]
Partial fix committed in https://github.com/phetsims/phet-io-sim-specific/commit/ad28597fb97d34faa27c0e378ee966fc89fbbd37

**Comment by samreid** [comment]
Fixed in the commits and working locally. Thanks for the issue @KatieWoe. Closing.
