### ISSUE TITLE
CT: Uncaught Error: Assertion failed: The launch button should only be enabled in phase: idle|showingCompleteSampleWithMean

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#141]
I saw this error on CT:

```
projectile-data-lab : phet-io-fuzz : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1707354721528/projectile-data-lab/projectile-data-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1707354721528%22%2C%22timestamp%22%3A1707355752070%7D&ea&brand=phet-io&phetioStandalone&fuzz
Query: ea&brand=phet-io&phetioStandalone&fuzz
Uncaught Error: Assertion failed: The launch button should only be enabled in phase: idle|showingCompleteSampleWithMean
Error: Assertion failed: The launch button should only be enabled in phase: idle|showingCompleteSampleWithMean
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1707354721528/assert/js/assert.js:28:13)
at assert (SamplingModel.ts:169:14)
at launchButtonPressed (PDLScreenView.ts:130:52)
at listener (TinyEmitter.ts:123:8)
at emit (Emitter.ts:62:21)
at emit (PushButtonModel.ts:201:22)
at fire (PushButtonModel.ts:143:15)
at listener (TinyEmitter.ts:123:8)
at emit (ReadOnlyProperty.ts:334:22)
at _notifyListeners (ReadOnlyProperty.ts:281:13)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1707354721528%2Fprojectile-data-lab%2Fprojectile-data-lab_en.html&simQueryParameters=ea%26brand%3Dphet-io%26phetioStandalone%26fuzz&testInfo=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1707354721528%22%2C%22timestamp%22%3A1707355752070%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1707354721528%2Fprojectile-data-lab%2Fprojectile-data-lab_en.html&simQueryParameters=ea%26brand%3Dphet-io%26phetioStandalone%26fuzz&testInfo=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1707354721528%22%2C%22timestamp%22%3A1707355752070%7D
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1707354721528/projectile-data-lab/projectile-data-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1707354721528%22%2C%22timestamp%22%3A1707355752070%7D&ea&brand=phet-io&phetioStandalone&fuzz
```

@matthew-blackman we wrote this a few days ago as a safety valve, but I'm not sure if it's revealing a true problem or an inconsistent intermediate state we can safely ignore. How should we proceed?

**Comment by matthew-blackman** [comment]
Let's discuss a bit more. I am not seeing how launchButtonPressed could be called with an intermediate state for phaseProperty. If that is the case, I'm good with reverting back to using the guard if all behavior is correct.

**Comment by samreid** [comment]
Our new assertion message revealed this error:

```
Uncaught Error: Assertion failed: The launch button should only be enabled in phase: idle | showingCompleteSampleWithMean.
Current phase: showingAirborneProjectiles

Number of started samples: 1

Number of completed samples: 0
Error: Assertion failed: The launch button should only be enabled in phase: idle | showingCompleteSampleWithMean.
```

This means the button was pressed when the sim was showing airborne projectiles.  I'll add one more debugging step

**Comment by samreid** [comment]
I added the next debugging step to see if the model DynamicProperty was in sync, and it was:

```
Uncaught Error: Assertion failed: The launch button should only be enabled in phase: idle | showingCompleteSampleWithMean
Current phase: showingAirborneProjectiles
Number of started samples: 1
Number of completed samples: 0
model.phase = showingAirborneProjectiles
```

The button.enabledProperty is queried here: https://github.com/phetsims/sun/blob/ec36af93832df90d5dc73e82eeb6059955011bdb/js/buttons/PushButtonModel.ts#L132-L144

Maybe we should try passing a DerivedProperty into the button.enabledProperty, in case that is updated sooner than the multilink.

**Comment by zepumph** [comment]
@samreid and I found an easy way to reproduce this. 

1. Go to sampling screen.
2. Press the launch button.
3. BEFORE the first sample lands, go to the second field
4. Click continuous
5. go back to the first field
6. Note that the launch button will be enabled and the projectiles will still be in mid air. 
7. Press the launch button before the projectiles land, and note the assertion.

**Comment by samreid** [comment]
Thanks to @zepumph we found a good solution to this problem, we committed it and also threw in another more strict assertion.  I think this issue can be closed.
