### ISSUE TITLE
CT: Assertion failed: linear requires a number to evaluate

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#189]
```
Uncaught Error: Assertion failed: linear requires a number to evaluate
Error: Assertion failed: linear requires a number to evaluate
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1708991466447/assert/js/assert.js:28:13)
at assert (Utils.js:520:14)
at linear (ProjectileSound.ts:31:15)
at playbackRateForPosition (MeanTone.ts:37:25)
at playMean (SamplingField.ts:343:17)
at step (SamplingModel.ts:261:29)
at step (Sim.ts:417:21)
at apply (PhetioAction.ts:162:16)
at execute (Sim.ts:1023:30)
at stepSimulation (Sim.ts:1013:11)
```

**Comment by samreid** [comment]
I added workarounds, but @matthew-blackman and I should try to find out why non-numbers were getting that far.

**Comment by samreid** [comment]
There is a significant chance this was solved in #182 and #193. We will leave the assertions on to see if CT thinks otherwise.

**Comment by samreid** [comment]
CT looks clear, let's leave the assertions on and close this issue. Nice work @matthew-blackman

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.
