### ISSUE TITLE
CT Designed API changes detected, please roll them back or revise the reference API

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/projectile-data-lab#282]
```
projectile-data-lab : phet-io-api-compatibility : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1712345163264/projectile-data-lab/projectile-data-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1712345163264%22%2C%22timestamp%22%3A1712345483303%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211&locales=*&webgl=false
Query: ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211&locales=*&webgl=false
Uncaught Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

PhET-iO Element missing: projectileDataLab.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.archetype.preferencesPanels.audioPreferencesPanel.launchSoundStrategyControl

PhET-iO Element missing: projectileDataLab.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.archetype.preferencesPanels.audioPreferencesPanel.playLandingSoundControl

New PhET-iO Element not in reference: projectileDataLab.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.archetype.preferencesPanels.audioPreferencesPanel.audioPreferences

projectileDataLab.measuresScreen.model.intervalTool.edge1Property.phetioFeatured changed from "false" to "true"

projectileDataLab.measuresScreen.model.intervalTool.edge2Property.phetioFeatured changed from "false" to "true"
Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1712345163264/assert/js/assert.js:28:13)
at assert (phetioEngine.ts:339:22)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1712345163264%2Fprojectile-data-lab%2Fprojectile-data-lab_en.html&simQueryParameters=ea%26brand%3Dphet-io%26phetioStandalone%26phetioCompareAPI%26randomSeed%3D332211%26locales%3D*%26webgl%3Dfalse&testInfo=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1712345163264%22%2C%22timestamp%22%3A1712345483303%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1712345163264%2Fprojectile-data-lab%2Fprojectile-data-lab_en.html&simQueryParameters=ea%26brand%3Dphet-io%26phetioStandalone%26phetioCompareAPI%26randomSeed%3D332211%26locales%3D*%26webgl%3Dfalse&testInfo=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1712345163264%22%2C%22timestamp%22%3A1712345483303%7D
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1712345163264/projectile-data-lab/projectile-data-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22projectile-data-lab%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1712345163264%22%2C%22timestamp%22%3A1712345483303%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211&locales=*&webgl=false
[CONSOLE] enabling assert
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

PhET-iO Element missing: projectileDataLab.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.archetype.preferencesPanels.audioPreferencesPanel.launchSoundStrategyControl

PhET-iO Element missing: projectileDataLab.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.archetype.preferencesPanels.audioPreferencesPanel.playLandingSoundControl

New PhET-iO Element not in reference: projectileDataLab.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.archetype.preferencesPanels.audioPreferencesPanel.audioPreferences

projectileDataLab.measuresScreen.model.intervalTool.edge1Property.phetioFeatured changed from "false" to "true"

projectileDataLab.measuresScreen.model.intervalTool.edge2Property.phetioFeatured changed from "false" to "true"
[PAGE ERROR] Error: Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

PhET-iO Element missing: projectileDataLab.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.archetype.preferencesPanels.audioPreferencesPanel.launchSoundStrategyControl

PhET-iO Element missing: projectileDataLab.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.archetype.preferencesPanels.audioPreferencesPanel.playLandingSoundControl

New PhET-iO Element not in reference: projectileDataLab.general.view.navigationBar.preferencesButton.preferencesDialogCapsule.archetype.preferencesPanels.audioPreferencesPanel.audioPreferences

projectileDataLab.measuresScreen.model.intervalTool.edge1Property.phetioFeatured changed from "false" to "true"

projectileDataLab.measuresScreen.model.intervalTool.edge2Property.phetioFeatured changed from "false" to "true"
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1712345163264/assert/js/assert.js:28:13)
at XMLHttpRequest.<anonymous> (http://128.138.93.172/continuous-testing/ct-snapshots/1712345163264/chipper/dist/js/phet-io/js/phetioEngine.js:282:23)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 4/5/2024, 1:26:03 PM
```

**Comment by samreid** [comment]
This will be addressed in https://github.com/phetsims/projectile-data-lab/issues/30, closing.
